# Numpy Cheatcodes

In [1]:
import numpy as np

# to make an array from numpy

In [2]:
a=np.array([1,56,76,8])

In [3]:
a

array([ 1, 56, 76,  8])

In [4]:
a=np.array([1,56,76,8],np.int8)

In [5]:
a     #for the dtype=int8 we have np.int8 

array([ 1, 56, 76,  8], dtype=int8)

In [6]:
a.shape #to have the shape of the array

(4,)

In [7]:
my=np.array([[1,2,3,5,4,3,21]])

In [8]:
my         #array of one row and 7 columns

array([[ 1,  2,  3,  5,  4,  3, 21]])

In [9]:
my.shape

(1, 7)

In [ ]:
myarr=np.array([[[1,2,5,7,8],[1,2,3,4,5],[8,9,0,1,2]]])

In [11]:
myarr.shape

(1, 3, 5)

In [12]:
myarr=np.array([[[1,2,5,7,8],
                 [1,2,3,4,5],
                 [8,9,0,1,2]]])

In [13]:
myarr.shape

(1, 3, 5)

In [15]:
my=np.zeros((2,3,4))

In [16]:
my

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
myarr=np.array([[[1,2],[2,1],[3,1]],[[2,1],[3,1],[4,1]]])


In [19]:
myarr


array([[[1, 2],
        [2, 1],
        [3, 1]],

       [[2, 1],
        [3, 1],
        [4, 1]]])

In [20]:
myarr.shape


(2, 3, 2)

In [26]:
myarr[1][0]

array([2, 1])

In [28]:
myarr=np.arange(15)

In [29]:
myarr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
myarr.shape

(15,)

In [45]:
myarr=np.arange(1000)

In [46]:
# We  use @ or dot function to have a matrix product for example A @ B or A.dot(B)

In [49]:
import random as rg

In [50]:
a=rg.random()

In [51]:
a


0.8943426115921753

In [55]:
b = np.arange(12).reshape(3,4)

In [56]:
b


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
b = np.arange(12).reshape(1,3,4)

In [61]:
b



array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])